Job launching after 0.47 seconds in submission.
Running python job.
Changed into dir /home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil
Importing evaluationFunctionXFoil.py
Running evaluationFunctionXFoil.main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spearmint-0.1-py2.7-linux-x86_64.egg/spearmint/launcher.py", line 245, in launch
    result = python_launcher(job)
  File "/usr/local/lib/python2.7/dist-packages/spearmint-0.1-py2.7-linux-x86_64.egg/spearmint/launcher.py", line 330, in python_launcher
    result = module.main(job['id'], params)
  File "/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/evaluationFunctionXFoil.py", line 65, in main
    return TwoDXFoilGame(job_id, params)
  File "/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/evaluationFunctionXFoil.py", line 57, in TwoDXFoilGame
    testgen = XFG.newGame(actions)
  File "/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/XFoilGame.py", line 110, in newGame
    self.Xfoil(testgen[2],self.Ncrit,self.Re, self.M, self.NoIter)
  File "/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/XFoilGame.py", line 72, in Xfoil
    resp = ps.stdout.read()
KeyboardInterrupt
Problem executing the function
Job failed in 17533.22 seconds.
(<type 'exceptions.KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x7fdd79f843f8>)
