2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] MongoDB starting : pid=15392 port=27017 dbpath=/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/ 64-bit host=simonx
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] db version v3.4.4
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] git version: 888390515874a9debd1b6c5d36559ca86b44babd
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] allocator: tcmalloc
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] modules: none
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] build environment:
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten]     distmod: ubuntu1404
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten]     distarch: x86_64
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten]     target_arch: x86_64
2017-04-22T20:48:01.348+0200 I CONTROL  [initandlisten] options: { processManagement: { fork: true }, storage: { dbPath: "datadir/" }, systemLog: { destination: "file", path: "logfile" } }
2017-04-22T20:48:01.383+0200 I -        [initandlisten] Detected data files in /home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/ created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
2017-04-22T20:48:01.383+0200 I STORAGE  [initandlisten] 
2017-04-22T20:48:01.383+0200 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-04-22T20:48:01.383+0200 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-04-22T20:48:01.383+0200 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=11495M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-04-22T20:48:01.661+0200 I CONTROL  [initandlisten] 
2017-04-22T20:48:01.661+0200 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-04-22T20:48:01.661+0200 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-04-22T20:48:01.661+0200 I CONTROL  [initandlisten] 
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] 
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] 
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-04-22T20:48:01.662+0200 I CONTROL  [initandlisten] 
2017-04-22T20:48:01.666+0200 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/home/simonx/Documents/Udacity/Projects/capstone/PESMOC_XFoil/SpearmintFiles/SecondTestandResultsCSTcontinue/datadir/diagnostic.data'
2017-04-22T20:48:01.666+0200 I NETWORK  [thread1] waiting for connections on port 27017
2017-04-22T20:48:02.125+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54128 #1 (1 connection now open)
2017-04-22T20:48:02.125+0200 I NETWORK  [conn1] received client metadata from 127.0.0.1:54128 conn1: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:48:02.126+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54130 #2 (2 connections now open)
2017-04-22T20:48:02.126+0200 I NETWORK  [conn2] received client metadata from 127.0.0.1:54130 conn2: { driver: { name: "PyMongo", version: "3.4.0" }, os: { type: "Linux", name: "Ubuntu 14.04 trusty", architecture: "x86_64", version: "4.4.0-72-generic" }, platform: "CPython 2.7.12.final.0" }
2017-04-22T20:48:14.478+0200 I -        [conn2] end connection 127.0.0.1:54130 (2 connections now open)
2017-04-22T20:48:14.478+0200 I -        [conn1] end connection 127.0.0.1:54128 (2 connections now open)
2017-04-22T21:12:59.661+0200 I NETWORK  [thread1] connection accepted from 127.0.0.1:54470 #3 (1 connection now open)
2017-04-22T21:12:59.662+0200 I NETWORK  [conn3] received client metadata from 127.0.0.1:54470 conn3: { application: { name: "MongoDB Shell" }, driver: { name: "MongoDB Internal Client", version: "3.4.4" }, os: { type: "Linux", name: "Ubuntu", architecture: "x86_64", version: "14.04" } }
2017-04-22T21:12:59.664+0200 I COMMAND  [conn3] terminating, shutdown command received
2017-04-22T21:12:59.664+0200 I NETWORK  [conn3] shutdown: going to close listening sockets...
2017-04-22T21:12:59.664+0200 I NETWORK  [conn3] closing listening socket: 7
2017-04-22T21:12:59.664+0200 I NETWORK  [conn3] closing listening socket: 8
2017-04-22T21:12:59.664+0200 I NETWORK  [conn3] removing socket file: /tmp/mongodb-27017.sock
2017-04-22T21:12:59.664+0200 I NETWORK  [conn3] shutdown: going to flush diaglog...
2017-04-22T21:12:59.664+0200 I FTDC     [conn3] Shutting down full-time diagnostic data capture
2017-04-22T21:12:59.669+0200 I STORAGE  [conn3] WiredTigerKVEngine shutting down
2017-04-22T21:12:59.686+0200 I STORAGE  [conn3] shutdown: removing fs lock...
2017-04-22T21:12:59.686+0200 I CONTROL  [conn3] now exiting
2017-04-22T21:12:59.686+0200 I CONTROL  [conn3] shutting down with code:0
